<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>Sentence Counter Report</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            color: #333;
            margin: 0;
            padding: 20px;
        }
        .header {
            text-align: center;
            border-bottom: 3px solid #06b6d4;
            padding-bottom: 15px;
            margin-bottom: 20px;
        }
        .header h1 {
            margin: 0;
            color: #0891b2;
        }
        .header p {
            margin: 5px 0 0 0;
            color: #666;
            font-size: 12px;
        }
        .section {
            margin-bottom: 25px;
        }
        .section-title {
            font-size: 14px;
            font-weight: bold;
            color: #0891b2;
            border-bottom: 2px solid #cffafe;
            padding-bottom: 8px;
            margin-bottom: 12px;
        }
        .metrics-grid {
            display: table;
            width: 100%;
            border-collapse: collapse;
        }
        .metric-row {
            display: table-row;
        }
        .metric-label {
            display: table-cell;
            padding: 8px;
            width: 50%;
            border-bottom: 1px solid #e5e7eb;
            font-weight: 600;
            color: #374151;
        }
        .metric-value {
            display: table-cell;
            padding: 8px;
            width: 50%;
            border-bottom: 1px solid #e5e7eb;
            text-align: right;
            color: #06b6d4;
            font-weight: bold;
        }
        .text-preview {
            background-color: #f9fafb;
            border: 1px solid #d1d5db;
            border-radius: 4px;
            padding: 12px;
            font-size: 12px;
            line-height: 1.6;
            color: #4b5563;
            max-height: 150px;
            overflow: hidden;
            margin: 10px 0;
        }
        .footer {
            border-top: 1px solid #d1d5db;
            padding-top: 15px;
            margin-top: 25px;
            font-size: 11px;
            color: #6b7280;
            text-align: center;
        }
    </style>
</head>
<body>
    <div class="header">
        <h1>Sentence Counter Analysis Report</h1>
        <p>Generated on {{ now()->format('Y-m-d H:i:s') }}</p>
    </div>

    {{-- Text Preview --}}
    <div class="section">
        <div class="section-title">Analyzed Text</div>
        <div class="text-preview">{{ substr($text, 0, 500) }}{{ strlen($text) > 500 ? '...' : '' }}</div>
    </div>

    {{-- Main Metrics --}}
    <div class="section">
        <div class="section-title">Sentence & Content Metrics</div>
        <div class="metrics-grid">
            <div class="metric-row">
                <div class="metric-label">Sentences</div>
                <div class="metric-value">{{ $result['sentences'] }}</div>
            </div>
            <div class="metric-row">
                <div class="metric-label">Words</div>
                <div class="metric-value">{{ $result['words'] }}</div>
            </div>
            <div class="metric-row">
                <div class="metric-label">Characters (with spaces)</div>
                <div class="metric-value">{{ $result['characters'] }}</div>
            </div>
            <div class="metric-row">
                <div class="metric-label">Characters (without spaces)</div>
                <div class="metric-value">{{ $result['characters_no_spaces'] }}</div>
            </div>
            <div class="metric-row">
                <div class="metric-label">Paragraphs</div>
                <div class="metric-value">{{ $result['paragraphs'] }}</div>
            </div>
        </div>
    </div>

    {{-- Averages & Time Estimates --}}
    <div class="section">
        <div class="section-title">Averages & Time Estimates</div>
        <div class="metrics-grid">
            <div class="metric-row">
                <div class="metric-label">Average Sentence Length</div>
                <div class="metric-value">{{ $result['avg_sentence_length'] }} words</div>
            </div>
            <div class="metric-row">
                <div class="metric-label">Reading Time (200 WPM)</div>
                <div class="metric-value">{{ $result['reading_time_minutes'] }} minute{{ $result['reading_time_minutes'] !== 1 ? 's' : '' }}</div>
            </div>
        </div>
    </div>

    <div class="footer">
        <p>{{ config('app.name', 'ToolsHub') }} Sentence Counter | Generated by {{ config('app.name', 'ToolsHub') }}</p>
    </div>
</body>
</html>
